# Generated by Django 4.2.30 on 2026-04-21 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('ward_number', models.CharField(blank=True, choices=[('1', 'Ward 1'), ('2', 'Ward 2'), ('3', 'Ward 3'), ('4', 'Ward 4'), ('5', 'Ward 5'), ('6', 'Ward 6'), ('7', 'Ward 7'), ('8', 'Ward 8'), ('9', 'Ward 9'), ('10', 'Ward 10'), ('11', 'Ward 11'), ('12', 'Ward 12'), ('13', 'Ward 13'), ('14', 'Ward 14'), ('15', 'Ward 15'), ('16', 'Ward 16'), ('17', 'Ward 17'), ('18', 'Ward 18'), ('19', 'Ward 19'), ('20', 'Ward 20'), ('21', 'Ward 21'), ('22', 'Ward 22'), ('23', 'Ward 23'), ('24', 'Ward 24'), ('25', 'Ward 25'), ('26', 'Ward 26'), ('27', 'Ward 27'), ('28', 'Ward 28'), ('29', 'Ward 29'), ('30', 'Ward 30'), ('31', 'Ward 31'), ('32', 'Ward 32'), ('33', 'Ward 33'), ('34', 'Ward 34'), ('35', 'Ward 35')], max_length=5)),
                ('aadhaar_last4', models.CharField(blank=True, max_length=4, verbose_name='Aadhaar Last 4 Digits')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('points', models.PositiveIntegerField(default=0)),
                ('total_reports', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Citizen Profile',
                'verbose_name_plural': 'Citizen Profiles',
            },
        ),
        migrations.CreateModel(
            name='CitizenCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=30, unique=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('points_at_issue', models.PositiveIntegerField()),
                ('milestone', models.PositiveIntegerField()),
                ('is_downloaded', models.BooleanField(default=False)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.citizenprofile')),
            ],
            options={
                'verbose_name': 'Best Citizen Certificate',
                'verbose_name_plural': 'Best Citizen Certificates',
                'ordering': ['-issued_date'],
            },
        ),
    ]
