# Generated by Django 6.0 on 2026-05-01 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otptoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(choices=[('tree_planter', 'Tree Planter')], max_length=50)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='accounts.citizenprofile')),
            ],
            options={
                'verbose_name': 'Citizen Badge',
                'verbose_name_plural': 'Citizen Badges',
                'ordering': ['-awarded_at'],
                'unique_together': {('citizen', 'badge')},
            },
        ),
    ]
