# Generated by Django 6.0 on 2026-05-01 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_image', models.ImageField(upload_to='environment_trees/%Y/%m/')),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment_saves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Environment Save',
                'verbose_name_plural': 'Environment Saves',
                'ordering': ['-created_at'],
            },
        ),
    ]
