# Generated by Django 6.0 on 2026-05-01 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_environmentsave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreePlantingCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=40, unique=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('tree_points', models.PositiveIntegerField(default=5)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_certificates', to=settings.AUTH_USER_MODEL)),
                ('environment_save', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='reports.environmentsave')),
            ],
            options={
                'verbose_name': 'Tree Planting Certificate',
                'verbose_name_plural': 'Tree Planting Certificates',
                'ordering': ['-issued_date'],
            },
        ),
    ]
