# Generated by Django 6.0 on 2026-05-01 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_treeplantingcertificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeMilestoneCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.PositiveIntegerField()),
                ('tree_points_at_issue', models.PositiveIntegerField()),
                ('trees_count_at_issue', models.PositiveIntegerField(default=0)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_milestone_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tree Milestone Certificate',
                'verbose_name_plural': 'Tree Milestone Certificates',
                'ordering': ['-issued_date'],
            },
        ),
    ]
